"""Control panel, OctoPrint and G-code in the Farm on Linux. Mirrors macOS
Tests/GantryTests/ControlAndGcodeTests.swift, plus the panel's own rules (jog and home G-code, motion
safety, card order) and the HTTP transfer requests."""
import base64
import json
import tempfile
import time
import unittest
import urllib.parse
from pathlib import Path
from types import SimpleNamespace

from gantry import transfer
from gantry.control import (BUSY_ORDER, IDLE_ORDER, card_order, home_gcode, is_motion_safe, jog_gcode,
                            motion_row_visible, takes_gcode)
from gantry.core import Printer, PrinterKind, PrinterState, Telemetry
from gantry.farm import (FarmError, FarmStore, gcode_plate, gcode_seconds, gcode_thumbnail, matches,
                         next_queue_item)
from gantry.http_clients import parse_octoprint
from gantry.smartplug import SmartPlug, parse_power

PRINTING = b'''{"state":{"text":"Printing","flags":{"operational":true,"printing":true,"paused":false,"ready":false}},
 "temperature":{"tool0":{"actual":214.8,"target":215},"bed":{"actual":59.9,"target":60}}}'''
JOB = b'{"job":{"file":{"name":"benchy.gcode","display":"benchy.gcode"}},"progress":{"completion":42.7,"printTimeLeft":1800},"state":"Printing"}'

GCODE = b"""; generated by PrusaSlicer 2.8.0
; thumbnail begin 16x16 12
; iVBORw0KGgo=
; thumbnail end
G28
G1 X10
; filament used [g] = 12.34, 0.00
; estimated printing time (normal mode) = 1h 2m 3s
; filament_type = PETG;PLA
; filament_colour = #FF0000;#00FF00
; nozzle_diameter = 0.4,0.4
; printer_model = MK4
"""


class OctoPrintParserTests(unittest.TestCase):
    def test_reads_state_temperatures_and_progress(self):
        t = parse_octoprint(PRINTING, JOB)
        self.assertEqual(t.state, PrinterState.PRINTING)
        self.assertEqual(t.nozzle, 214.8)
        self.assertEqual(t.bed_target, 60)
        self.assertEqual(t.progress, 42)
        self.assertEqual(t.remaining_minutes, 30)
        self.assertEqual(t.job_name, "benchy.gcode")

    def test_no_printer_connected_is_offline(self):
        self.assertEqual(parse_octoprint(None, None).state, PrinterState.OFFLINE)

    def test_a_completed_job_reads_as_finished(self):
        idle = b'{"state":{"flags":{"operational":true,"ready":true}},"temperature":{}}'
        done = b'{"job":{"file":{"name":"a.gcode"}},"progress":{"completion":100}}'
        t = parse_octoprint(idle, done)
        self.assertEqual(t.state, PrinterState.FINISHED)
        self.assertIsNone(t.remaining_minutes)

    def test_paused_and_error_flags(self):
        paused = b'{"state":{"flags":{"operational":true,"paused":true,"printing":false}}}'
        self.assertEqual(parse_octoprint(paused).state, PrinterState.PAUSED)
        failed = b'{"state":{"flags":{"closedOrError":true,"operational":false}}}'
        self.assertEqual(parse_octoprint(failed).state, PrinterState.ERROR)

    def test_octoprint_is_its_own_kind(self):
        printer = Printer.from_dict({"serial": "octoprint-10.0.0.8", "name": "Ender", "host": "10.0.0.8", "kind": "octoprint"})
        self.assertEqual(printer.kind, PrinterKind.OCTOPRINT)
        self.assertEqual(printer.port, 80)


class GcodeLibraryTests(unittest.TestCase):
    def test_reads_slicer_metadata_from_comments(self):
        plate = gcode_plate(GCODE)
        self.assertEqual(plate["seconds"], 3723)
        self.assertEqual(plate["nozzle"], 0.4)
        self.assertEqual(plate["printerModel"], "MK4")
        self.assertEqual([f["material"] for f in plate["filaments"]], ["PETG"])
        self.assertEqual(plate["filaments"][0]["grams"], 12.34)
        self.assertEqual(plate["filaments"][0]["color"], "#FF0000")

    def test_extracts_the_embedded_thumbnail(self):
        self.assertEqual(gcode_thumbnail(GCODE), base64.b64decode("iVBORw0KGgo="))

    def test_the_largest_thumbnail_wins(self):
        small, large = base64.b64encode(b"small").decode(), base64.b64encode(b"large").decode()
        data = (f"; thumbnail begin 16x16 8\n; {small}\n; thumbnail end\n"
                f"; thumbnail begin 300x300 8\n; {large}\n; thumbnail end\n").encode()
        self.assertEqual(gcode_thumbnail(data), b"large")

    def test_cura_time_is_plain_seconds(self):
        self.assertEqual(gcode_plate(b";FLAVOR:Marlin\n;TIME:5400\nG28\n")["seconds"], 5400)
        self.assertEqual(gcode_seconds("1d 0h 1m 5s"), 86465)
        self.assertIsNone(gcode_seconds("soon"))

    def test_each_printer_gets_only_the_files_it_can_print(self):
        self.assertTrue(transfer.accepts(PrinterKind.BAMBU, "3mf"))
        self.assertFalse(transfer.accepts(PrinterKind.BAMBU, "gcode"))
        self.assertTrue(transfer.accepts(PrinterKind.KLIPPER, "gcode"))
        self.assertTrue(transfer.accepts(PrinterKind.OCTOPRINT, "GCODE"))
        self.assertFalse(transfer.accepts(PrinterKind.OCTOPRINT, "bgcode"))
        self.assertTrue(transfer.accepts(PrinterKind.PRUSA, "bgcode"))
        self.assertFalse(transfer.accepts(PrinterKind.ELEGOO_CC1, "gcode"))

    def test_gcode_queue_items_go_only_to_their_printers(self):
        item = {"copies": 1, "printers": ["K1"], "plate": {"index": 1, "filaments": []}, "format": "gcode"}
        klipper = lambda fmt: transfer.accepts(PrinterKind.KLIPPER, fmt or "3mf")  # noqa: E731
        self.assertEqual(next_queue_item([item], "K1", Telemetry(), accepts=klipper), (0, []))
        self.assertIsNone(next_queue_item([item], "K2", Telemetry(), accepts=klipper))
        # A Bambu printer never takes a G-code item, even when named.
        self.assertIsNone(next_queue_item([item], "K1", Telemetry()))

    def test_matches_the_job_whatever_extension_the_printer_reports(self):
        job = {"remoteName": "gantry-1a2b3c4d.gcode"}
        self.assertTrue(matches(job, Telemetry(job_name="gantry-1a2b3c4d.gcode")))
        self.assertTrue(matches(job, Telemetry(job_name="gantry-1a2b3c4d")))
        self.assertFalse(matches({"remoteName": "gantry-other.gcode"}, Telemetry(job_name="gantry-1a2b3c4d")))
        # Bambu still reports its 3MF without the extension.
        self.assertTrue(matches({"remoteName": "gantry-x.3mf"}, Telemetry(job_name="gantry-x")))


class TransferRequestTests(unittest.TestCase):
    def _printer(self, kind, port=None):
        return Printer("S", "P", "10.0.0.7", port=port or kind.default_port, kind=kind)

    def test_klipper_upload_is_multipart_into_gcodes_and_start_names_the_file(self):
        request = transfer.upload_request(self._printer(PrinterKind.KLIPPER), None, b"G28\n", "gantry-1a2b3c4d.gcode")
        self.assertEqual((request.method, request.url), ("POST", "http://10.0.0.7:7125/server/files/upload"))
        self.assertIn(b'name="root"\r\n\r\ngcodes', request.body)
        self.assertIn(b'filename="gantry-1a2b3c4d.gcode"', request.body)
        self.assertNotIn("X-Api-Key", request.headers)
        start = transfer.start_request(self._printer(PrinterKind.KLIPPER), None, "gantry-1a2b3c4d.gcode")
        self.assertEqual(start.url, "http://10.0.0.7:7125/printer/print/start?filename=gantry-1a2b3c4d.gcode")

    def test_octoprint_uploads_without_printing_then_selects_and_prints(self):
        printer = self._printer(PrinterKind.OCTOPRINT)
        request = transfer.upload_request(printer, "KEY", b"G28\n", "gantry-1a2b3c4d.gcode")
        self.assertEqual(request.url, "http://10.0.0.7:80/api/files/local")
        self.assertEqual(request.headers["X-Api-Key"], "KEY")
        self.assertIn(b'name="print"\r\n\r\nfalse', request.body)
        self.assertIn(b'name="select"\r\n\r\nfalse', request.body)
        start = transfer.start_request(printer, "KEY", "gantry-1a2b3c4d.gcode")
        self.assertEqual(start.url, "http://10.0.0.7:80/api/files/local/gantry-1a2b3c4d.gcode")
        self.assertEqual(json.loads(start.body), {"command": "select", "print": True})

    def test_prusalink_puts_to_usb_and_never_prints_after_upload(self):
        printer = self._printer(PrinterKind.PRUSA)
        request = transfer.upload_request(printer, "KEY", b"data", "gantry-1a2b3c4d.bgcode")
        self.assertEqual((request.method, request.url), ("PUT", "http://10.0.0.7:80/api/v1/files/usb/gantry-1a2b3c4d.bgcode"))
        self.assertEqual(request.headers["Print-After-Upload"], "?0")
        self.assertEqual(request.body, b"data")
        self.assertEqual(transfer.start_request(printer, "KEY", "gantry-1a2b3c4d.bgcode").method, "POST")

    def test_other_printers_and_bad_addresses_are_refused(self):
        with self.assertRaises(transfer.TransferError):
            transfer.upload_request(self._printer(PrinterKind.BAMBU), None, b"", "a.gcode")
        with self.assertRaises(transfer.TransferError):
            transfer.start_request(Printer("S", "P", "10.0.0.7/evil", kind=PrinterKind.KLIPPER, port=7125), None, "a.gcode")


class MotionTests(unittest.TestCase):
    def test_jog_is_relative_and_returns_to_absolute(self):
        self.assertEqual(jog_gcode(x=10), "G91\nG1 X10.00 F3000\nG90")
        self.assertEqual(jog_gcode(y=-1), "G91\nG1 Y-1.00 F3000\nG90")
        self.assertEqual(jog_gcode(z=1), "G91\nG1 Z1.00 F600\nG90")
        self.assertIsNone(jog_gcode())

    def test_home(self):
        self.assertEqual(home_gcode(), "G28")
        self.assertEqual(home_gcode("xy"), "G28 X Y")
        self.assertEqual(home_gcode("Z"), "G28 Z")

    def test_motion_only_when_nothing_prints(self):
        self.assertTrue(is_motion_safe(PrinterState.IDLE))
        self.assertTrue(is_motion_safe(PrinterState.FINISHED))
        for state in (PrinterState.PRINTING, PrinterState.PAUSED, PrinterState.ERROR, PrinterState.OFFLINE):
            self.assertFalse(is_motion_safe(state))

    def test_which_printers_take_gcode_controls(self):
        self.assertTrue(takes_gcode(PrinterKind.KLIPPER, False))
        self.assertTrue(takes_gcode(PrinterKind.OCTOPRINT, False))
        self.assertTrue(takes_gcode(PrinterKind.BAMBU, False))
        self.assertFalse(takes_gcode(PrinterKind.BAMBU, True))
        self.assertFalse(takes_gcode(PrinterKind.PRUSA, False))

    def test_card_order_follows_the_printer(self):
        self.assertEqual(card_order(True), BUSY_ORDER)
        self.assertEqual(card_order(True)[:3], ("print", "thermal", "power"))
        self.assertEqual(card_order(False)[:2], ("send", "motion"))
        self.assertEqual(sorted(IDLE_ORDER), sorted(BUSY_ORDER))

    def test_motion_folds_away_while_printing_or_unsupported(self):
        self.assertTrue(motion_row_visible(True, False, True))
        self.assertTrue(motion_row_visible(False, False, True), "idle with control off: shown but disabled")
        self.assertFalse(motion_row_visible(False, True, True))
        self.assertFalse(motion_row_visible(False, False, False))


class SmartPlugPowerTests(unittest.TestCase):
    def test_reads_watts_from_each_metering_socket(self):
        self.assertEqual(parse_power("shellyRPC", 1, '{"id":0,"output":true,"apower":123.4}'), 123.4)
        self.assertEqual(parse_power("tasmota", 1, '{"StatusSNS":{"ENERGY":{"Power":87}}}'), 87)
        self.assertEqual(parse_power("tasmota", 2, '{"StatusSNS":{"ENERGY":{"Power":[10,20]}}}'), 20)
        self.assertEqual(parse_power("shelly", 1, '{"meters":[{"power":55.5}]}'), 55.5)
        self.assertIsNone(parse_power("homeAssistant", 1, '{"state":"on"}'))

    def test_tasmota_meter_asks_for_status_8(self):
        request = SmartPlug(kind="tasmota", host="10.0.0.5").power_request(None)
        self.assertIn("cmnd=Status%208", request.full_url)
        self.assertEqual(dict(urllib.parse.parse_qsl(urllib.parse.urlsplit(request.full_url).query))["cmnd"], "Status 8")

    def test_which_sockets_meter(self):
        self.assertTrue(SmartPlug(kind="shellyRPC").meters)
        self.assertFalse(SmartPlug(kind="homeAssistant").meters)
        self.assertIsNone(SmartPlug(kind="http", onURL="http://a", offURL="http://b").power_request(None))


class _Secrets:
    def get(self, key):
        return None


class GcodeStoreTests(unittest.TestCase):
    def _setup(self, state=PrinterState.IDLE):
        root = Path(tempfile.mkdtemp())
        sent, started = [], []
        printers = [SimpleNamespace(serial="K1", name="Voron", host="10.0.0.7", port=7125, kind=PrinterKind.KLIPPER),
                    SimpleNamespace(serial="X1", name="X1C", host="10.0.0.5", port=8883, kind=PrinterKind.BAMBU)]
        app = SimpleNamespace(printers=printers, telemetry={"K1": Telemetry(state=state), "X1": Telemetry()},
                              telemetry_seen={"K1": time.time(), "X1": time.time()}, secrets=_Secrets(),
                              send_command=lambda serial, payload: True, requires_signed_commands=lambda serial: False)

        def sender(printer, code, local, remote, progress, cancelled):
            sent.append((printer.serial, Path(local).read_bytes(), remote))
            progress(1.0)
        store = FarmStore(app, root=root, sender=sender, starter=lambda printer, code, remote: started.append(remote),
                          run_async=lambda job: job())
        source = root / "benchy.gcode"
        source.write_bytes(GCODE)
        return store, app, sent, started, source

    def test_import_upload_and_explicit_start(self):
        store, app, sent, started, source = self._setup()
        file = store.import_file(str(source))
        self.assertEqual(file["format"], "gcode")
        self.assertTrue(store.preview_path(file["id"], 1).exists())
        with self.assertRaises(FarmError):
            store.upload_to(file, file["plates"][0], app.printers[1], [])   # Bambu takes 3MF only
        store.upload_to(file, file["plates"][0], app.printers[0], [])
        job = store.jobs[0]
        self.assertRegex(job["remoteName"], r"^gantry-[0-9a-f]{8}\.gcode$")
        self.assertEqual(sent, [("K1", GCODE, job["remoteName"])])
        self.assertEqual(job["state"], "uploaded")
        self.assertEqual(started, [])
        store.start(job["id"], True, True)
        self.assertEqual(started, [job["remoteName"]])
        self.assertEqual(job["state"], "awaitingStart")

    def test_gcode_queue_needs_named_printers_then_starts_by_itself(self):
        store, app, sent, started, source = self._setup()
        file = store.import_file(str(source))
        with self.assertRaises(FarmError):
            store.enqueue(file, file["plates"][0], 1, [])
        with self.assertRaises(FarmError):
            store.enqueue(file, file["plates"][0], 1, ["X1"])
        store.enqueue(file, file["plates"][0], 1, ["K1"])
        self.assertEqual(sent, [])
        store.arm("K1")
        self.assertEqual(len(sent), 1)
        self.assertEqual(len(started), 1)
        self.assertEqual(store.queue, [])

    def test_a_failed_start_is_uncertain_and_never_retried(self):
        store, app, sent, started, source = self._setup()

        def refuse(printer, code, remote):
            raise transfer.TransferError("HTTP 409")
        store.starter = refuse
        file = store.import_file(str(source))
        store.upload_to(file, file["plates"][0], app.printers[0], [])
        store.start(store.jobs[0]["id"], True, True)
        self.assertEqual(store.jobs[0]["state"], "uncertain")


try:
    from gantry import app as gantry_app
    from gantry.controlpanel import JogPad, key_move, send_lines
except Exception:  # pragma: no cover - GTK bindings missing on this host
    gantry_app = None


@unittest.skipIf(gantry_app is None, "gantry.app needs the GTK bindings")
class AppControlTests(unittest.TestCase):
    def _app(self, state=PrinterState.IDLE):
        app = gantry_app.Gantry.__new__(gantry_app.Gantry)
        app.printers = [Printer("X1", "X1C", "10.0.0.5", kind=PrinterKind.BAMBU),
                        Printer("O1", "Ender", "10.0.0.8", port=80, kind=PrinterKind.OCTOPRINT),
                        Printer("P1", "MK4", "10.0.0.9", port=80, kind=PrinterKind.PRUSA)]
        app.telemetry = {serial: Telemetry(state=state) for serial in ("X1", "O1", "P1")}
        app.sent_commands, app.sent_gcode, app.actions = [], [], []
        app.send_command = lambda serial, text: (app.sent_commands.append((serial, json.loads(text))), True)[1]
        app.send_gcode = lambda serial, text: (app.sent_gcode.append((serial, text)), True)[1]
        connection = SimpleNamespace(job_action=lambda action: app.actions.append(action) or True)
        app.connections = {"O1": connection, "P1": connection}
        app.detail_window = None
        return app

    def test_octoprint_jogs_homes_and_sets_fans_with_gcode(self):
        app = self._app()
        self.assertTrue(app.jog("O1", x=10))
        self.assertTrue(app.home("O1", "XY"))
        app.set_fan("O1", 1, 50)
        self.assertEqual(app.sent_gcode, [("O1", "G91\nG1 X10.00 F3000\nG90"), ("O1", "G28 X Y"), ("O1", "M106 S127")])

    def test_motion_is_refused_mid_print_and_on_printers_without_gcode(self):
        app = self._app(PrinterState.PRINTING)
        self.assertFalse(app.jog("O1", z=1))
        self.assertFalse(app.home("X1"))
        app.telemetry["P1"] = Telemetry(state=PrinterState.IDLE)
        self.assertFalse(app.jog("P1", x=1))
        self.assertEqual(app.sent_gcode + app.sent_commands, [])

    def test_bambu_that_wants_signed_commands_takes_no_motion(self):
        app = self._app()
        app.telemetry["X1"].command_signing_required = True
        self.assertFalse(app.accepts_gcode("X1"))
        self.assertFalse(app.home("X1"))
        app.telemetry["X1"].command_signing_required = False
        self.assertTrue(app.home("X1"))
        self.assertEqual(app.sent_commands[0][1]["print"]["param"], "G28\n")

    def test_print_actions_reach_every_brand(self):
        app = self._app(PrinterState.PRINTING)
        app.send_print_action("O1", "pause")
        app.send_print_action("P1", "stop")
        app.send_print_action("X1", "resume")
        deadline = time.time() + 2
        while len(app.actions) < 2 and time.time() < deadline:
            time.sleep(0.01)
        self.assertEqual(sorted(app.actions), ["pause", "stop"])
        self.assertEqual(app.sent_commands[0][1]["print"]["command"], "resume")

    def test_keys_over_the_panel(self):
        from gi.repository import Gdk
        self.assertEqual(key_move(Gdk.KEY_Left, False), (-1.0, 0.0, 0.0))
        self.assertEqual(key_move(Gdk.KEY_Up, True), (0.0, 10.0, 0.0))
        self.assertEqual(key_move(Gdk.KEY_Page_Down, False), (0.0, 0.0, -1.0))
        self.assertEqual(key_move(Gdk.KEY_h, False), "home")
        self.assertIsNone(key_move(Gdk.KEY_a, False))

    def test_jog_pad_rings(self):
        self.assertEqual(JogPad.hit(180, 180, 90, 90), (-1, 0))
        self.assertEqual(JogPad.hit(180, 180, 90, 40), (0, 1.0))       # inner ring, up: +Y 1 mm
        self.assertEqual(JogPad.hit(180, 180, 170, 90), (1, 10.0))     # outer ring, right: +X 10 mm
        self.assertIsNone(JogPad.hit(180, 180, 2, 2))

    def test_send_dialog_lines(self):
        lines = send_lines({"seconds": 3723, "filaments": [{"material": "PETG", "grams": 12.3}]}, "AMS")
        self.assertEqual(len(lines), 4)
        self.assertIn("1 h 02 min", lines[0])
        self.assertIn("PETG 12 g", lines[1])


if __name__ == "__main__":
    unittest.main()
