#!/usr/bin/env python3
"""Write web/assets/tokens.css from the shipped design contract.

The page is a fourth port of the same fleet card, so it must not carry its own idea of the colours and
geometry. Everything it needs comes from design/gantry-card-layout.impl.json, the file the macOS,
Windows and GNU/Linux ports are checked against.

Run it after changing the contract; `--check` fails instead of writing, which is what the parity check
uses to prove the page did not drift.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACT = json.loads((ROOT / "design/gantry-card-layout.impl.json").read_text(encoding="utf-8"))
OUTPUT = ROOT / "web/assets/tokens.css"


def rgba(value: str) -> str:
    """The contract writes rgba without spaces; CSS is happy either way, so pass it through."""
    return value


def build() -> str:
    tokens = CONTRACT["tokens"]
    surface = tokens["surface"]
    thermal = tokens["thermal"]
    radius = tokens["radius"]
    fleet = CONTRACT["fleet"]
    card = CONTRACT["card"]
    group = CONTRACT["filamentGroup"]
    slot = CONTRACT["filamentSlot"]
    bar = CONTRACT["progressBar"]
    bento = CONTRACT["tempBento"]
    dock = CONTRACT["filamentDock"]

    lines = [
        "/* Generated by scripts/build_web_theme.py from design/gantry-card-layout.impl.json.",
        f"   Contract {CONTRACT['meta']['version']}. Do not edit by hand: run the script. */",
        ":root {",
        f"    --canvas: {surface['canvas']};",
        f"    --card: {surface['fleetCard']};",
        f"    --card-alpha: {surface['fleetCardAlpha']};",
        f"    --card-line: {rgba(surface['fleetCardLine'])};",
        f"    --line: {rgba(surface['line'])};",
        f"    --text: {surface['text']};",
        f"    --secondary: {surface['secondary']};",
        f"    --muted: {surface['muted']};",
        f"    --accent: {surface['accent']};",
        f"    --nozzle: {thermal['nozzle']};",
        f"    --bed: {thermal['bed']};",
        f"    --chamber: {thermal['chamber']};",
        f"    --humidity: {thermal['humidity']};",
        f"    --sensor-temp: {thermal['sensorTemp']};",
        f"    --status-printing: {tokens['status']['printing']};",
        f"    --status-paused: {tokens['status']['paused']};",
        f"    --radius-card: {radius['card']}px;",
        f"    --radius-tile: {radius['tile']}px;",
        f"    --radius-chip: {radius['chip']}px;",
        f"    --radius-swatch: {radius['swatchFill']}px;",
        f"    --gap: {tokens['gap']}px;",
        f"    --card-gap: {fleet['columnGap']}px;",
        f"    --card-width: {CONTRACT['floatingWindow']['tileResize']['card']['width']}px;",
        f"    --card-min-height: {CONTRACT['floatingWindow']['tileResize']['card']['height']}px;",
        f"    --card-inset-x: {card['contentInset']['left']}px;",
        f"    --card-inset-y: {card['contentInset']['top']}px;",
        f"    --section-gap: {card['sectionSpacing']}px;",
        f"    --header-gap: {CONTRACT['header']['spacing']}px;",
        f"    --status-gap: {CONTRACT['statusRow']['spacing']}px;",
        f"    --summary-gap: {CONTRACT['progressSummary']['spacing']}px;",
        f"    --bar-height: {bar['height']}px;",
        f"    --bar-segments: {bar['segments']};",
        f"    --bar-segment-gap: {bar['segmentGap']}px;",
        f"    --bar-segment-radius: {bar['segmentRadius']}px;",
        f"    --bar-inactive: rgba(242, 243, 241, 0.12);",
        f"    --bento-height: {bento['height']}px;",
        f"    --bento-zone-bg: {rgba(bento['zone']['bg'])};",
        f"    --group-bg: {rgba(group['background'])};",
        f"    --group-radius: {group['radius']}px;",
        f"    --group-inset-x: {group['inset']['left']}px;",
        f"    --group-inset-y: {group['inset']['top']}px;",
        f"    --group-gap: {dock['groupGap']}px;",
        f"    --group-header-gap: {group['headerToSlotsSpacing']}px;",
        f"    --slot-gap: {group['slots']['spacing']}px;",
        f"    --swatch-height: {slot['swatchHeight']}px;",
        f"    --swatch-max-ams: {slot['swatchMaxWidth']['ams']}px;",
        f"    --swatch-max-ext: {slot['swatchMaxWidth']['ext']}px;",
        f"    --swatch-border-active: {rgba(slot['borderActive']['color'])};",
        f"    --swatch-border-present: {rgba(slot['borderPresent']['color'])};",
        f"    --pill-bg: {rgba(CONTRACT['header']['manufacturerPill']['bg'])};",
        f"    --pill-radius: {CONTRACT['header']['manufacturerPill']['radius']}px;",
        f"    --chip-bg: {rgba(CONTRACT['header']['actionsButton']['bg'])};",
        "}",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    generated = build()
    if "--check" in sys.argv:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current != generated:
            print("web/assets/tokens.css is out of date: run scripts/build_web_theme.py")
            return 1
        print(f"web theme OK — tokens match contract {CONTRACT['meta']['version']}")
        return 0
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} from contract {CONTRACT['meta']['version']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
