const translations={
  en:{navFeatures:'Features',navPlatforms:'Platforms',download:'Download',eyebrow:'Your workshop. Live.',heroLine1:'Every printer.',heroLine2:'One clear view.',heroLead:'A local 3D printer fleet monitor. Status, progress, temperatures and filament — without the cloud or five different apps.',downloadFree:'Download free',seeAction:'See it in action',noCloud:'No cloud',printing:'Printing',overview:'OVERVIEW',statement:'Stop watching printers.<br><em>Let Gantry watch them for you.</em>',statementCopy:'One lightweight tool gathers the essentials from your whole workshop and puts them exactly where you need them.',localFirst:'Local first',staysLan:'Your data stays on your LAN',capabilities:'CAPABILITIES',everything:'Everything important.<br><em>Nothing noisy.</em>',liveStatus:'Live status',liveStatusCopy:'Progress, ETA, layers, temperatures and job state in one calm view.',filamentCopy:'Colors, active slots, humidity and temperature for filament modules.',notifications:'Notifications',notificationsCopy:'Errors, completed jobs and material problems without staring at the printer.',fleetScale:'From one printer to a whole farm',fleetScaleCopy:'Adaptive layout, compact mode and persistent card order. Five or fifteen devices — the interface stays readable.',everywhere:'EVERYWHERE',nativePlace:'Right at home.<br><em>On every system.</em>',macTitle:'Always one click away.',macCopy:'A native menu bar popover. One click reveals your entire workshop.',minutes:'Your workshop in Gantry.<br><em>In a few minutes.</em>',stepDownload:'Download the app',stepDownloadCopy:'Choose the build for your operating system from the latest release.',stepDiscover:'Discover devices',stepDiscoverCopy:'Gantry scans your local network or imports your Bambu Studio configuration.',stepMonitor:'Print with confidence',stepMonitorCopy:'Statuses, filament and alerts appear automatically.',builtOpen:'Built in the open.<br><em>For the community.</em>',sourceCopy:'MIT licensed. No hidden telemetry. No account. No features locked behind a subscription.',questions:'Questions.<br><em>Short answers.</em>',faqCloud:'Does Gantry require an account or cloud?',faqCloudA:'No. Gantry talks to printers directly over your local network.',faqPrinters:'Which printers are supported?',faqPrintersA:'Bambu Lab, Klipper/Moonraker devices and PrusaLink. More systems are in development.',faqCodes:'Where are access codes stored?',faqCodesA:'macOS can use Keychain, Windows uses DPAPI and Linux uses Secret Service.',faqPrice:'How much does Gantry cost?',faqPriceA:'Nothing. Gantry is free and available under the MIT license.',cta:'Check less.<br><em>Print more.</em>',ctaCopy:'Your workshop deserves one good screen.',downloadGantry:'Download Gantry',footerTag:'A local 3D printer status monitor.',support:'Support the project'},
  pl:{}
};
document.querySelectorAll('[data-i18n]').forEach(element=>{
  translations.pl[element.dataset.i18n]=element.innerHTML;
});
const platformData={
  mac:{label:'MACOS',image:'assets/mac.png',alt:'Gantry na macOS',pl:{title:'Zawsze pod ręką.',copy:'Natywne okno przy pasku menu. Jedno kliknięcie i widzisz cały warsztat.',points:['Menu bar popover','macOS Keychain','Start przy logowaniu']},en:{title:'Always one click away.',copy:'A native menu bar popover. One click reveals your entire workshop.',points:['Menu bar popover','macOS Keychain','Launch at login']}},
  win:{label:'WINDOWS',image:'assets/win.png',alt:'Gantry na Windows',pl:{title:'Naturalnie w zasobniku.',copy:'Panel otwiera się bezpośrednio z paska zadań i nie przeszkadza w codziennej pracy.',points:['System tray','Szyfrowanie DPAPI','Instalator i portable']},en:{title:'Naturally in the tray.',copy:'The panel opens directly from the taskbar and stays out of your way.',points:['System tray','DPAPI encryption','Installer and portable']}},
  linux:{label:'GNU/LINUX',image:'assets/linux.png',alt:'Gantry na GNU/Linux',pl:{title:'Lekki i systemowy.',copy:'Wersja GTK integruje się z popularnymi środowiskami linuksowymi.',points:['GTK 3','Secret Service','.deb package']},en:{title:'Lightweight and native.',copy:'The GTK build integrates with popular Linux desktop environments.',points:['GTK 3','Secret Service','.deb package']}},
  pi:{label:'RASPBERRY PI',image:'assets/pi.png',alt:'Gantry kiosk na Raspberry Pi',pl:{title:'Ekran dla warsztatu.',copy:'Pełnoekranowy kiosk zmienia mały komputer w stałe centrum monitoringu.',points:['Tryb kiosk','Widok 24/7','Import CSV']},en:{title:'A screen for the workshop.',copy:'Full-screen kiosk mode turns a small computer into a permanent monitoring station.',points:['Kiosk mode','24/7 overview','CSV import']}}
};
let language='pl';
const languageButton=document.querySelector('.language');
function setLanguage(next){language=next;document.documentElement.lang=next;languageButton.textContent=next==='pl'?'PL':'EN';document.querySelectorAll('[data-i18n]').forEach(el=>{const value=translations[next]?.[el.dataset.i18n];if(value)el.innerHTML=value});const active=document.querySelector('.platform-tabs .active')?.dataset.platform||'mac';setPlatform(active)}
languageButton.addEventListener('click',()=>setLanguage(language==='pl'?'en':'pl'));
function setPlatform(key){const data=platformData[key],copy=data[language];document.querySelectorAll('.platform-tabs button').forEach(b=>{const active=b.dataset.platform===key;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});document.querySelector('#platform-label').textContent=data.label;document.querySelector('#platform-title').textContent=copy.title;document.querySelector('#platform-description').textContent=copy.copy;document.querySelector('#platform-points').innerHTML=copy.points.map(point=>`<li>${point}</li>`).join('');const image=document.querySelector('#platform-image');image.src=data.image;image.alt=data.alt}
document.querySelectorAll('.platform-tabs button').forEach(button=>button.addEventListener('click',()=>setPlatform(button.dataset.platform)));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.13});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const tilt=document.querySelector('[data-tilt]');if(tilt&&!matchMedia('(prefers-reduced-motion: reduce)').matches){document.querySelector('.hero-stage').addEventListener('pointermove',event=>{const rect=event.currentTarget.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width-.5,y=(event.clientY-rect.top)/rect.height-.5;tilt.style.transform=`rotateY(${x*7-7}deg) rotateX(${-y*5+2}deg) rotateZ(1.2deg)`});document.querySelector('.hero-stage').addEventListener('pointerleave',()=>tilt.style.transform='rotateY(-7deg) rotateX(2deg) rotateZ(1.2deg)')}
setLanguage('pl');
