import Foundation
import Testing
@testable import Gantry

@Suite struct OctoPrintStatusParserTests {
    private let printing = """
    {"state":{"text":"Printing","flags":{"operational":true,"printing":true,"paused":false,"ready":false}},
     "temperature":{"tool0":{"actual":214.8,"target":215},"bed":{"actual":59.9,"target":60}}}
    """
    private let job = """
    {"job":{"file":{"name":"benchy.gcode","display":"benchy.gcode"}},"progress":{"completion":42.7,"printTimeLeft":1800},"state":"Printing"}
    """

    @Test func readsStateTemperaturesAndProgress() {
        let t = OctoPrintStatusParser.telemetry(printer: Data(printing.utf8), job: Data(job.utf8))
        #expect(t.state == .printing)
        #expect(t.nozzleTemperature == 214.8)
        #expect(t.bedTargetTemperature == 60)
        #expect(t.progress == 42)
        #expect(t.remainingMinutes == 30)
        #expect(t.jobName == "benchy.gcode")
    }

    @Test func noPrinterConnectedIsOffline() {
        #expect(OctoPrintStatusParser.telemetry(printer: nil, job: nil).state == .offline)
    }

    @Test func aCompletedJobReadsAsFinished() {
        let idle = #"{"state":{"flags":{"operational":true,"ready":true}},"temperature":{}}"#
        let done = #"{"job":{"file":{"name":"a.gcode"}},"progress":{"completion":100}}"#
        let t = OctoPrintStatusParser.telemetry(printer: Data(idle.utf8), job: Data(done.utf8))
        #expect(t.state == .finished)
        #expect(t.remainingMinutes == nil)
    }
}

@Suite struct GcodeLibraryTests {
    private let gcode = """
    ; generated by PrusaSlicer 2.8.0
    ; thumbnail begin 16x16 12
    ; iVBORw0KGgo=
    ; thumbnail end
    G28
    G1 X10
    ; filament used [g] = 12.34, 0.00
    ; estimated printing time (normal mode) = 1h 2m 3s
    ; filament_type = PETG;PLA
    ; filament_colour = #FF0000;#00FF00
    ; nozzle_diameter = 0.4,0.4
    ; printer_model = MK4
    """

    @Test func readsSlicerMetadataFromComments() {
        let plate = FarmGcode.plate(Data(gcode.utf8))
        #expect(plate.seconds == 3723)
        #expect(plate.nozzle == 0.4)
        #expect(plate.printerModel == "MK4")
        #expect(plate.filaments.map(\.material) == ["PETG"])
        #expect(plate.filaments.first?.grams == 12.34)
        #expect(plate.filaments.first?.color == "#FF0000")
    }

    @Test func extractsTheEmbeddedThumbnail() {
        #expect(FarmGcode.thumbnail(Data(gcode.utf8)) == Data(base64Encoded: "iVBORw0KGgo="))
    }

    @Test func curaTimeIsPlainSeconds() {
        #expect(FarmGcode.plate(Data(";FLAVOR:Marlin\n;TIME:5400\nG28\n".utf8)).seconds == 5400)
    }

    @Test func eachPrinterGetsOnlyTheFilesItCanPrint() {
        #expect(PrinterFileTransfer.accepts(.bambu, fileExtension: "3mf"))
        #expect(!PrinterFileTransfer.accepts(.bambu, fileExtension: "gcode"))
        #expect(PrinterFileTransfer.accepts(.klipper, fileExtension: "gcode"))
        #expect(PrinterFileTransfer.accepts(.octoprint, fileExtension: "GCODE"))
        #expect(!PrinterFileTransfer.accepts(.octoprint, fileExtension: "bgcode"))
        #expect(PrinterFileTransfer.accepts(.prusa, fileExtension: "bgcode"))
        #expect(!PrinterFileTransfer.accepts(.elegooCC1, fileExtension: "gcode"))
    }

    @Test func gcodeQueueItemsGoOnlyToTheirPrinters() {
        let item = FarmQueueItem(id: UUID(), fileID: UUID(), fileName: "a.gcode", plate: FarmPlate(index: 1),
                                 copies: 1, printers: ["K1"], createdAt: Date(), format: "gcode")
        let gcode: (String?) -> Bool = { PrinterFileTransfer.accepts(.klipper, fileExtension: $0 ?? "3mf") }
        #expect(FarmRules.nextQueueItem([item], serial: "K1", telemetry: PrinterTelemetry(), accepts: gcode)?.mapping == [])
        #expect(FarmRules.nextQueueItem([item], serial: "K2", telemetry: PrinterTelemetry(), accepts: gcode) == nil)
        // A Bambu printer never takes a G-code item, even when named.
        #expect(FarmRules.nextQueueItem([item], serial: "K1", telemetry: PrinterTelemetry()) == nil)
    }

    @Test func matchesTheJobWhateverExtensionThePrinterReports() {
        var job = FarmJob(id: UUID(), fileID: UUID(), fileName: "a.gcode", serial: "K1", printerName: "K1",
                          plate: FarmPlate(index: 1), mapping: [], remoteName: "gantry-1a2b3c4d.gcode",
                          state: .awaitingStart, message: "", createdAt: Date(), updatedAt: Date())
        var t = PrinterTelemetry()
        t.jobName = "gantry-1a2b3c4d.gcode"
        #expect(FarmRules.matches(job, t))
        t.jobName = "gantry-1a2b3c4d"
        #expect(FarmRules.matches(job, t))
        job.remoteName = "gantry-other.gcode"
        #expect(!FarmRules.matches(job, t))
        #expect(job.isGcode)
    }
}

@Suite struct SmartPlugPowerTests {
    @Test func readsWattsFromEachMeteringSocket() {
        #expect(SmartPlug.parsePower(kind: .shellyRPC, channel: 1, data: Data(#"{"id":0,"output":true,"apower":123.4}"#.utf8)) == 123.4)
        #expect(SmartPlug.parsePower(kind: .tasmota, channel: 1, data: Data(#"{"StatusSNS":{"ENERGY":{"Power":87}}}"#.utf8)) == 87)
        #expect(SmartPlug.parsePower(kind: .tasmota, channel: 2, data: Data(#"{"StatusSNS":{"ENERGY":{"Power":[10,20]}}}"#.utf8)) == 20)
        #expect(SmartPlug.parsePower(kind: .shelly, channel: 1, data: Data(#"{"meters":[{"power":55.5}]}"#.utf8)) == 55.5)
        #expect(SmartPlug.parsePower(kind: .homeAssistant, channel: 1, data: Data(#"{"state":"on"}"#.utf8)) == nil)
    }

    @Test func tasmotaMeterAsksForStatus8() {
        let request = SmartPlug(kind: .tasmota, host: "10.0.0.5").powerRequest(secret: nil)
        #expect(request?.url?.absoluteString.contains("cmnd=Status%208") == true)
    }
}
